# Generated by Django 4.2.8 on 2024-01-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=256, verbose_name='author')),
                ('img_user', models.ImageField(upload_to='author-imgs/', verbose_name='image of the author ')),
            ],
        ),
    ]
