# Generated by Django 4.2.8 on 2024-01-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_author_img_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='img_user',
        ),
        migrations.AddField(
            model_name='author',
            name='img',
            field=models.ImageField(default=1, upload_to='pinterest_img/', verbose_name='img of the post'),
            preserve_default=False,
        ),
    ]
