# Generated by Django 4.2.8 on 2024-01-20 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pinterest', '0002_remove_card_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='name of the post')),
                ('descriptions', models.TextField(verbose_name='descriptions for the post')),
                ('img', models.ImageField(upload_to='pinterest_img/', verbose_name='image of the post')),
                ('date', models.DateField(verbose_name='date of the post')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ('date',),
            },
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
