# Generated by Django 4.2.8 on 2024-01-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0003_post_delete_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_user',
            field=models.ImageField(default=2, upload_to='pinterest_img_user/', verbose_name='img of the user'),
            preserve_default=False,
        ),
    ]
