# Generated by Django 4.2.8 on 2024-01-21 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_author_img_user'),
        ('pinterest', '0004_post_img_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='accounts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.author', verbose_name='Author'),
            preserve_default=False,
        ),
    ]
