# Generated by Django 4.2.8 on 2024-01-21 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0006_remove_post_img_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='accounts',
        ),
    ]
