# Generated by Django 4.2.8 on 2024-01-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0007_remove_post_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
